// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4J4j36GxJny-om9et9qAWd4XzzLp27Kg',
    appId: '1:775944185232:web:f58acf1ef9da417595bf15',
    messagingSenderId: '775944185232',
    projectId: 'lab10-4-a439f',
    authDomain: 'lab10-4-a439f.firebaseapp.com',
    storageBucket: 'lab10-4-a439f.firebasestorage.app',
    measurementId: 'G-SNDN230JEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2h8pLSv0KEGYxvmmBFaXDVTfou8oG0Hw',
    appId: '1:775944185232:android:a1a613b9a97e381595bf15',
    messagingSenderId: '775944185232',
    projectId: 'lab10-4-a439f',
    storageBucket: 'lab10-4-a439f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmpxOz9U277Y7VMDwZIWGE34rb-DMyrtc',
    appId: '1:775944185232:ios:500d6017be7fa9ce95bf15',
    messagingSenderId: '775944185232',
    projectId: 'lab10-4-a439f',
    storageBucket: 'lab10-4-a439f.firebasestorage.app',
    androidClientId: '775944185232-jein57jh7t2gls7hgfjcqec1qas8379h.apps.googleusercontent.com',
    iosClientId: '775944185232-7av0ptn59kpdi5kscj7l2pfua1k7q7i6.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab104',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4J4j36GxJny-om9et9qAWd4XzzLp27Kg',
    appId: '1:775944185232:web:abe303dd3a4a492995bf15',
    messagingSenderId: '775944185232',
    projectId: 'lab10-4-a439f',
    authDomain: 'lab10-4-a439f.firebaseapp.com',
    storageBucket: 'lab10-4-a439f.firebasestorage.app',
    measurementId: 'G-EMKL0MJ8JG',
  );
}